### PR TITLE
upgrade to operator sdk1.x

### PR DESCRIPTION
**Pull request by raffaelespazzoli**
also includes:
1. refactoring to propagate context
2. bugfix on IsSamePatches

### CODE REVIEW

**Comment by sabre1041** [comment]
@raffaelespazzoli can you make a request for the necessary Quay repositories to support the desired CI actions

**Comment by raffaelespazzoli** [comment]
> @raffaelespazzoli can you make a request for the necessary Quay repositories to support the desired CI actions

done: https://github.com/redhat-cop/org/issues/304

**Comment by raffaelespazzoli** [comment]
fixes #26

**Review by sabre1041 — APPROVED** [review]
LGTM

**Pull request merged**
