### PR TITLE
add requeueAfter variants, add convenience function. Fixes #48

### LINKED ISSUE #48: feature: add optional `requeueAfter` to manageError/manageSuccess
Sometimes one would want to requeue after a given internal, typically when reconciliation depends on cluster-external resources.
Could a `requeueAfter` parameter be added to these methods to support that?
That would avoid boilerplate like:
```
func (r *GithubActionRunnerReconciler) manageOutcome(ctx context.Context, instance* garov1alpha1.GithubActionRunner, issue error) (reconcile.Result, error) {
	var result reconcile.Result
	var err error
	if issue != nil {
		result, err = r.ManageError(ctx, instance, issue)
	} else {
		result, err = r.ManageSuccess(ctx, instance)
	}
	result.RequeueAfter = instance.Spec.GetReconciliationPeriod()

	return result, err
}
```

### PR DESCRIPTION
**Pull request by davidkarlsen**
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

### CODE REVIEW

**Comment by davidkarlsen** [comment]
A bit strange that the example controllers don't use the utility method, but this PR should work.

**Comment by raffaelespazzoli** [comment]
So, this is not what I thought you were proposing, I though you wanted to propose a `manageOutcome` method with the reschedule time.
Here is how I'd like to do it: we create two new methods `manageErrorWithRetryTime` and manageSuccessWithRetryTime` with the logic that you have identified. Then we make the existing methods call the new methods, with zero time.
I don't want to change the existing methods which are for convenience and are likely good in 95% of the scenarios.

**Comment by davidkarlsen** [comment]
sure, I'll get back with a fixed PR.
BTW: Any reason for the example controllers not to use the helper-methods?

**Comment by raffaelespazzoli** [comment]
I'm good with this PR if:
```golang
reconcile.Result{RequeueAfter: 0} == reconcile.Result{}
```
that is to say if in a standard situation this code does not change the current behavior. 
Can you make sure of that? To see why this is important also look at: https://github.com/kubernetes-sigs/controller-runtime/blob/f7a3dc6a7650289b6ca7afca12b97819329b0d06/pkg/reconcile/reconcile.go#L36

**Comment by davidkarlsen** [comment]
According to spec it should not matter: https://github.com/kubernetes-sigs/controller-runtime/blob/f7a3dc6a7650289b6ca7afca12b97819329b0d06/pkg/reconcile/reconcile.go#L31
I've checked for references for IsZero and the only reference I can find is in the tests.

**Comment by davidkarlsen** [comment]
https://github.com/kubernetes-sigs/controller-runtime/blob/2b423ec0a6646ad7fec022f76aa7c94358dc1135/pkg/internal/controller/controller.go#L269
Since it is a struct with a time (which is a literal) it will be zero initialized anyway - so it should be the same anyways.

**Comment by raffaelespazzoli** [comment]
ok,can you add a bit of documentation on the newly added function. Please find a spot that seems proper to you in the current docs.

**Comment by davidkarlsen** [comment]
Are you thinking of the readme as I already added golang docs.

**Comment by davidkarlsen** [comment]
@raffaelespazzoli docs added - ptal.
Can you also make a new release/tag?

**Pull request merged**
